package solution
package gcounter







































}	}		}			g.counts[replicaID] = count		if count > g.counts[replicaID] {	for replicaID, count := range other.counts {func (g *GCounter) Merge(other *GCounter) {// Takes the max of each replica's count to ensure convergence.// Merge combines another G-Counter's state into this one.}	return total	}		total += count	for _, count := range g.counts {	total := 0func (g *GCounter) Value() int {// Value returns the sum of all replica counts.}	g.counts[g.replicaID]++func (g *GCounter) Increment() {// Increment increases this replica's count by 1.}	}		counts:    make(map[string]int),		replicaID: replicaID,	return &GCounter{func NewGCounter(replicaID string) *GCounter {// NewGCounter creates a new G-Counter for the given replica.}	counts    map[string]int	replicaID stringtype GCounter struct {// Each replica tracks increments in a vector; merge takes max per replica.// GCounter is a grow-only counter CRDT.