package solution
package gcounter

import (
	"testing"
)
















































































































































































































































}	}		t.Errorf("Expected value 2 after merging zero-value replica, got %d", gcA.Value())	if gcA.Value() != 2 {	gcA.Merge(gcB)	// Merge B into A (should have no effect since B=0)	// B doesn't increment (stays at 0)	gcA.Increment()	gcA.Increment()	// A increments	gcB := NewGCounter("B")	gcA := NewGCounter("A")func TestGCounterZeroValueReplica(t *testing.T) {}	}		t.Errorf("Expected value 6 (1 + 2 + 3), got %d", gcA.Value())	if gcA.Value() != 6 {	gcA.Merge(gcC)	// When A merges C, A should have all three replicas	gcC.Increment()	gcC.Increment()	gcC.Increment()	gcC := NewGCounter("C")	// C only has its own updates	gcA.Merge(gcB)	gcB.Increment()	gcB.Increment()	gcA.Increment()	gcB := NewGCounter("B")	gcA := NewGCounter("A")	// A has seen updates from A and Bfunc TestGCounterPartialMerge(t *testing.T) {}	}		t.Errorf("Expected value 6, got %d", gcA.Value())	if gcA.Value() != 6 {	gcA.Merge(gcC)	gcA.Merge(gcB)	// Merge all into A	gcC.Increment()	gcC.Increment()	gcC.Increment()	gcB.Increment()	gcB.Increment()	gcA.Increment()	gcC := NewGCounter("C")	gcB := NewGCounter("B")	gcA := NewGCounter("A")func TestGCounterThreeReplicas(t *testing.T) {}	}		t.Errorf("Expected value 2 after self-merge, got %d", gc.Value())	if gc.Value() != 2 {	gc.Merge(gc)	// Merge with self (should be idempotent)	gc.Increment()	gc.Increment()	gc := NewGCounter("A")func TestGCounterMergeWithSelf(t *testing.T) {}	}		t.Errorf("Expected value 6, got %d", value1)	if value1 != 6 {	}		t.Errorf("Merge is not associative: (A←B)←C=%d, A←(B←C)=%d", value1, value2)	if value1 != value2 {	value2 := gcA2.Value()	gcA2.Merge(gcB2)	gcB2.Merge(gcC2)	gcC2.Increment()	gcC2.Increment()	gcC2.Increment()	gcB2.Increment()	gcB2.Increment()	gcA2.Increment()	gcC2 := NewGCounter("C")	gcB2 := NewGCounter("B")	gcA2 := NewGCounter("A")	// Scenario 2: A ← (B ← C)	value1 := gcA1.Value()	gcA1.Merge(gcC1)	gcA1.Merge(gcB1)	gcC1.Increment()	gcC1.Increment()	gcC1.Increment()	gcB1.Increment()	gcB1.Increment()	gcA1.Increment()	gcC1 := NewGCounter("C")	gcB1 := NewGCounter("B")	gcA1 := NewGCounter("A")	// Scenario 1: (A ← B) ← Cfunc TestGCounterMergeAssociative(t *testing.T) {}	}		t.Errorf("Expected value 10, got %d", value1)	if value1 != 10 {	}		t.Errorf("Merge is not commutative: A←B←C=%d, A←C←B=%d", value1, value2)	if value1 != value2 {	value2 := gcA2.Value()	gcA2.Merge(gcB2)	gcA2.Merge(gcC2)	}		gcC2.Increment()	for i := 0; i < 5; i++ {	}		gcB2.Increment()	for i := 0; i < 2; i++ {	}		gcA2.Increment()	for i := 0; i < 3; i++ {	gcC2 := NewGCounter("C")	gcB2 := NewGCounter("B")	gcA2 := NewGCounter("A")	// Scenario 2: A ← C ← B	value1 := gcA1.Value()	gcA1.Merge(gcC1)	gcA1.Merge(gcB1)	}		gcC1.Increment()	for i := 0; i < 5; i++ {	}		gcB1.Increment()	for i := 0; i < 2; i++ {	}		gcA1.Increment()	for i := 0; i < 3; i++ {	gcC1 := NewGCounter("C")	gcB1 := NewGCounter("B")	gcA1 := NewGCounter("A")	// Scenario 1: A ← B ← Cfunc TestGCounterMergeCommutative(t *testing.T) {}	}		t.Errorf("Expected value 5, got %d", secondValue)	if secondValue != 5 {	}		t.Errorf("Merge is not idempotent: first=%d, second=%d", firstValue, secondValue)	if firstValue != secondValue {	secondValue := gcA.Value()	gcA.Merge(gcB)	// Second merge (should have no effect)	firstValue := gcA.Value()	gcA.Merge(gcB)	// First merge	gcB.Increment()	gcB.Increment()	gcA.Increment()	gcA.Increment()	gcA.Increment()	gcB := NewGCounter("B")	gcA := NewGCounter("A")func TestGCounterMergeIdempotent(t *testing.T) {}	}		t.Errorf("Expected value 5 after merge, got %d", gcA.Value())	if gcA.Value() != 5 {	gcA.Merge(gcB)	// Merge B into A	}		gcB.Increment()	for i := 0; i < 2; i++ {	// B increments 2 times	}		gcA.Increment()	for i := 0; i < 3; i++ {	// A increments 3 times	gcB := NewGCounter("B")	gcA := NewGCounter("A")func TestGCounterMergeTwoReplicas(t *testing.T) {}	}		t.Errorf("Expected value 5 after 5 increments, got %d", gc.Value())	if gc.Value() != 5 {	}		gc.Increment()	for i := 0; i < 5; i++ {	gc := NewGCounter("A")func TestGCounterMultipleIncrements(t *testing.T) {}	}		t.Errorf("Expected value 1 after increment, got %d", gc.Value())	if gc.Value() != 1 {	gc.Increment()	gc := NewGCounter("A")func TestGCounterSingleIncrement(t *testing.T) {}	}		t.Errorf("Expected initial value 0, got %d", gc.Value())	if gc.Value() != 0 {	gc := NewGCounter("A")func TestGCounterInitialValue(t *testing.T) {